name: Build and deploy to master branch

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: yarn install
    - run: yarn lint
    - run: yarn build
    - run: git config user.email "jeromewus@gmail.com"
    - run: git config user.name "Jerome Wu"
    - run: yarn run deploy --repo https://${{ secrets.ACCESS_TOKEN }}@github.com/ffmpegjs/ffmpegjs.github.io.git
