name: Build and deploy to master branch

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: yarn install
    - run: yarn lint
    - run: yarn build

    - name: Deploy	
      uses: JamesIves/github-pages-deploy-action@releases/v3	
      with:	
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}	
        BASE_BRANCH	: develop	
        BRANCH: master	
        FOLDER: build
